### ISSUE TITLE
Extra setup for distillery

### ISSUE THREAD

**Issue by akoutmos** [thoughtbot/redbird#7]
I recently tried pulling this into my project and while I am able to use redbird when running mix phx.server or via iex -S mix, when I package up my application with distillery redbird seems to fail. Below is the error that I get:
```
[info] Application redbird exited: Redbird.start(:normal, []) returned an error: shutdown: failed to start child: Redbird.Redis
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:connection_error, {:connection_error, :econnrefused}}}
            (redbird) lib/redis.ex:3: Redbird.Redis.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I'll do some more digging around to see what's going on, but does this seem to be an issue with redbird or with distillery?

**Comment by akoutmos** [comment]
Nevermind. This section in the distillery docs cleared it up for me https://hexdocs.pm/distillery/getting-started.html#application-configuration

**Comment by drapergeek** [comment]
Glad you found the problem. Cheers!

**Comment by rchodha** [comment]
@akoutmos Hey there, I'm facing the same issue.
Can you share the solution.
Also, this link you shared isn't working for me.
